name: Pull Request Laravel

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Run Update From Main Branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}

    - name: Cache composer dependencies
      uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-
    - name: Install PHP
      uses: shivammathur@setup-php@v2
      with:
        php-version: 8.2
    - name: Install Composer
      run: |
        composer install --no-interaction
    - name: Run Migration
      run: |
        php artisan migrate --force
    # - name: Optimize and Dump Loader
    #   run: |
    #     php artisan optimize:clear && composer dump-autoload
